var shell = require('shelljs'),
    fs = require('fs');

var config = {
    title: 'My Blog',
    subtitle: "This is the subtitle",
    author: 'Mr. Unknown',
    keywords: 'wanna blog',
    description: 'This is a blog generated by wanna.',
    theme: 'default'
}

function init() {
    shell.mkdir('-p', 'posts');
    shell.mkdir('-p', 'pages');
    shell.mkdir('-p', 'themes');

    if (shell.test('-f', 'config.json')) {
        console.log('"config.json" existed!');
        console.log('Please check if a wanna blog existed in current directory, "init" command should be executed only in an uninitialized directory.');
    } else {
        var txt = JSON.stringify(config).replace(/,/g, ',\n    ').replace('{', '{\n    ').replace('}', '\n}');
        fs.writeFileSync('config.json', txt, 'utf-8');
        console.log('A new wanna blog initialized');
    }
}

module.exports = {
    command: 'init',
    description: '\tinit a wanna blog',
    action: init
};
