var shell = require('shelljs'),
    fs = require('fs');

var config = {
    title: 'My Blog',
    subtitle: "This is the subtitle",
    author: 'Mr. Unknown',
    keywords: 'wanna blog',
    description: 'This is a blog generated by wanna.',
    theme: 'default'
}

function init(options) {
    shell.mkdir('-p', 'posts');
    shell.mkdir('-p', 'pages');
    shell.mkdir('-p', 'themes');

    if (shell.test('-f', 'config.json')) {
        console.log('"config.json" existed!');
        console.log('Please check if a wanna blog existed in current directory, "init" command should be executed only in an uninitialized directory.');
    } else {
        for (var i in config) {
            config[i] = options[i] || config[i];
        }
        var txt = JSON.stringify(config).replace(/,/g, ',\n    ').replace('{', '{\n    ').replace('}', '\n}');
        fs.writeFileSync('config.json', txt, 'utf-8');
        console.log('A new wanna blog initialized.');
    }
}

module.exports = {
    command: 'init',
    description: '\tinit a wanna blog',
    options: [
        ['-t, --title <title>', 'specify blog title. Or you can change it later by modifying config.json.'],
        ['-s, --subtitle <subtitle>', 'specify blog subtitle. Or you can change it later by modifying config.json.'],
        ['-a, --author <author>', 'specify blog author. Or you can change it later by modifying config.json.'],
        ['-k, --keywords <keywords>', 'specify blog keywords. Or you can change it later by modifying config.json.'],
        ['-d, --description <description>', 'specify blog description. Or you can change it later by modifying config.json.'],
        ['-T, --theme <theme>', 'specify blog theme. Or you can change it later by modifying config.json.']
    ],
    action: init
};
